services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: mehran.admin
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    networks:
      - blockchain-net

  neo4j:
    image: neo4j:5.26-community
    container_name: neo4j
    ports:
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data
    networks:
      - blockchain-net

volumes:
  clickhouse_data:
  neo4j_data:

networks:
  blockchain-net:
    external: true
